import gpxpy

from src.ham.radio.radio_additional import RadioAdditional
from src.ham.util import radio_types
from src.ham.util.file_util import RadioWriter


class RadioAdditionalGpx(RadioAdditional):
	def __init__(self, channels, dmr_ids, digital_contacts, zones, users):
		super().__init__(channels, dmr_ids, digital_contacts, zones, users)

	def output(self):
		gpx = gpxpy.gpx.GPX()
		gpx.name = 'Ham Radio Stations'
		gpx.description = 'Ham radio station locations generated by Ham Radio Sync'

		for channel in self._channels:
			if channel.latitude.fmt_val() is None or channel.longitude.fmt_val() is None:
				continue

			gpx_waypoint = gpxpy.gpx.GPXWaypoint()
			gpx_waypoint.latitude = channel.latitude.fmt_val()
			gpx_waypoint.longitude = channel.longitude.fmt_val()
			gpx_waypoint.name = channel.name.fmt_val()
			gpx_waypoint.description = f"Rx: {channel.rx_freq.fmt_val():0.03f} Tx offset: {channel.tx_offset.fmt_val(0):0.03f}"
			gpx.waypoints.append(gpx_waypoint)

		xml = gpx.to_xml()
		writer = RadioWriter.output_writer(f'{radio_types.GPX}/{radio_types.GPX}.gpx', '\r\n')
		writer.write_raw(xml)
		writer.close()
